DROP DATABASE IF EXISTS maintenance_db;

CREATE DATABASE maintenance_db;

\c maintenance_db


CREATE TABLE users(
  id serial primary key,
  name varchar NOT NULL,
  email varchar UNIQUE NOT NULL,
  password_digest varchar NOT NULL,
  user_type varchar NOT NULL  DEFAULT 'client'
);

CREATE TABLE companies (
     comp_id SERIAL PRIMARY KEY,
     comp_name VARCHAR,
     comp_description text,
     comp_logo text,
     users_id INT , 
     foreign key(users_id) references users
);

CREATE TABLE clients (
    client_id SERIAL PRIMARY KEY,
    client_name VARCHAR,
    client_type VARCHAR,
    users_id INT , 
    foreign key(users_id) references users
);


CREATE TABLE contracts (
    contract_id SERIAL PRIMARY KEY,
    contract_period INT,
    contract_status VARCHAR,
    contract_issue_date date,
    company_id INT NOT NULL,
    client_id INT NOT NULL,
    foreign key(company_id) references companies,
    foreign key(client_id) references clients
);


 INSERT INTO companies(comp_name,comp_description,comp_logo) 
 VALUES ('SABACO',`1. make sure the services are described in the contract and its schedules. It sounds obvious, but experience shows that many ignore this basic point, and live to rue the day. After all the fuzzy sales talk, it's easy to think you and the supplier are of the same mind about what is going to be delivered. But you need to write it down. And it's amazing how often writing it down shows there are some things you disagree on. When you have written it down, think about whether there is ambiguity. Suppose the cost of the service is to be by reference to the number of employees who use it. Is "employees" enough? Would it be better for you to refer to "full time equivalents"? The financial consequences of loose drafting can be very significant.
2. Measuring the standard to which the service is delivered is crucial. The supplier will have some well worn objective measures, response times, service availability, etc. Think about whether these really reflect what is important to your business (as opposed to what the supplier is confident it can do). If not, think about alternative measures. It is also worth running some mock scenarios against the service credits to test how they might apply in live situations. Does it really matter if there is a service interruption at 4am? Should it have the same consequences as a service interruption at 4pm? It's also worth making sure that the financial impact of any service credits is realistic: token service credits are pointless; punitive service credits can damage the relationship. Be prepared to think innovatively about service measurement and reward. For example, some current thinking involves rewards going direct to the supplier's delivery team as personal bonuses.
3. FM contracts are a long game, and things change. Will the service you buy today meet your business' needs in three years time? In reality, the shape of your business is likely to change significantly through things such as organic growth or even shrinkage, acquisition or divestment, taking on new sites, consolidating others, establishing new service lines, dropping others. It's vital that the contract has built in enough flexibility – in terms of services and pricing – to allow you to manage business change. Your lawyers will be able to advise you on the options for change control. In many instances it is important to be able to compel the supplier to accept changes. As well as a clear change management process, effective contracts will have transparent pricing for specific service lines so that both parties can approach change with a degree of certainty.
4. You're expecting great things, but what if the service is woeful, and threatens your business? It's critical to build in rights to terminate when the supplier does not deliver to its promises. Most contracts will contain a general termination right where the supplier is in material breach. Think about whether this needs to be supplemented with specific rights of termination for some performance defaults, for example failure to achieve service levels for three consecutive months. Specific rights can give a degree of certainty in difficult situations. On the subject of difficult situations, think about a contractual dispute resolution procedure. This can provide for escalation through to senior management if an intractable dispute arises. It is also worth thinking about alternatives to litigation for resolving disputes. Arbitration can work well, and it's confidential so there's less chance of bad publicity. But take care in multi‑party situations. If some parties are signed up to arbitration and others are not, life can get messy.
5. Disputes are one thing, but the relationship may not work for commercial reasons. What looks like a good deal today can turn out to be uncompetitive in three years' time. An effective price and quality benchmarking process should help control this risk, but sometimes it is necessary to terminate early. A well drawn agreement will give this right to terminate for convenience and provide for the financial consequences of this. It's best to avoid more nebulous statements about how this sum will be calculated, such as "the supplier's unrecovered costs plus an element of profit". This just provides scope for argument. A fully worked formula or spreadsheet agreed at the outset will mean that both sides know where they stand.
6. Whenever and however the end of the relationship comes to an end, it's crucial to document what assistance the supplier will provide on exit. It's amazing how many signed contracts have an exit schedule which simply says "to be completed as soon as possible after contract signature". It's even more amazing that the schedule is not looked at again until the eve of termination, by which time relations between supplier and customer may not be the best. Exit should be recognised and treated as a project in itself, and documented as such. Agreeing a detailed exit schedule in advance will resolve many uncertainties at what is bound to be a tense time.
7. What should the exit schedule address? It will vary from contract to contract, of course, but customers will want to ensure that they end up with (or at least have the option of ending up with) the means of providing the relevant services. This might mean hand back of premises or physical property, and these will need to be in a proper state so the customer can use them. Think also about handover of know how. It's no use having the kit if your people don't know how to use it. There may be other less obvious material which will be needed such as data which the supplier may have collected over the life of the project.
8. Employees may be a central issue on exit. From a practical, operational perspective, particular individuals may be key to the delivery of the service. From a legal perspective, TUPE may well impact on the rights and liabilities of the supplier, customer and the relevant employees (just as it might have done on entry into the contract). TUPE can present significant uncertainties on exit, so it may be best to deal with it at the outset.
9. Who pays for exit? It's crucial to decide this up-front. Obviously much will depend on the strength of your bargaining position, but all one-way traffic may not be a great idea. Suppliers perform best when incentivised. Given that the supplier may be reluctant about giving up the contract, it's not surprising that it may be tempted to "work to rule" in this situation. And working to rule often isn't good enough on exit when you need the supplier to go the extra mile. Some financial reward to smooth the way may work wonders.
10. Finally, just as contracts need to be flexible, so do exit schedules. As the shape of the contract evolves, it's important to ensure that the exit arrangements reflect this. Any major change should include a review of the impacts on exit. And it's good practice to review and update the exit schedule annually.`,'https://www.freeiconspng.com/uploads/company-icon--desktop-business-icons--softiconsm-23.png'),
  ('MUNEERA',`1. Make sure the services are described in the contract and its schedules. It sounds obvious, but experience shows that many ignore this basic point, and live to rue the day. After all the fuzzy sales talk, it's easy to think you and the supplier are of the same mind about what is going to be delivered. But you need to write it down. And it's amazing how often writing it down shows there are some things you disagree on. When you have written it down, think about whether there is ambiguity. Suppose the cost of the service is to be by reference to the number of employees who use it. Is "employees" enough? Would it be better for you to refer to "full time equivalents"? The financial consequences of loose drafting can be very significant.
2. Measuring the standard to which the service is delivered is crucial. The supplier will have some well worn objective measures, response times, service availability, etc. Think about whether these really reflect what is important to your business (as opposed to what the supplier is confident it can do). If not, think about alternative measures. It is also worth running some mock scenarios against the service credits to test how they might apply in live situations. Does it really matter if there is a service interruption at 4am? Should it have the same consequences as a service interruption at 4pm? It's also worth making sure that the financial impact of any service credits is realistic: token service credits are pointless; punitive service credits can damage the relationship. Be prepared to think innovatively about service measurement and reward. For example, some current thinking involves rewards going direct to the supplier's delivery team as personal bonuses.
3. FM contracts are a long game, and things change. Will the service you buy today meet your business' needs in three years time? In reality, the shape of your business is likely to change significantly through things such as organic growth or even shrinkage, acquisition or divestment, taking on new sites, consolidating others, establishing new service lines, dropping others. It's vital that the contract has built in enough flexibility – in terms of services and pricing – to allow you to manage business change. Your lawyers will be able to advise you on the options for change control. In many instances it is important to be able to compel the supplier to accept changes. As well as a clear change management process, effective contracts will have transparent pricing for specific service lines so that both parties can approach change with a degree of certainty.
4. You're expecting great things, but what if the service is woeful, and threatens your business? It's critical to build in rights to terminate when the supplier does not deliver to its promises. Most contracts will contain a general termination right where the supplier is in material breach. Think about whether this needs to be supplemented with specific rights of termination for some performance defaults, for example failure to achieve service levels for three consecutive months. Specific rights can give a degree of certainty in difficult situations. On the subject of difficult situations, think about a contractual dispute resolution procedure. This can provide for escalation through to senior management if an intractable dispute arises. It is also worth thinking about alternatives to litigation for resolving disputes. Arbitration can work well, and it's confidential so there's less chance of bad publicity. But take care in multi‑party situations. If some parties are signed up to arbitration and others are not, life can get messy.
5. Disputes are one thing, but the relationship may not work for commercial reasons. What looks like a good deal today can turn out to be uncompetitive in three years' time. An effective price and quality benchmarking process should help control this risk, but sometimes it is necessary to terminate early. A well drawn agreement will give this right to terminate for convenience and provide for the financial consequences of this. It's best to avoid more nebulous statements about how this sum will be calculated, such as "the supplier's unrecovered costs plus an element of profit". This just provides scope for argument. A fully worked formula or spreadsheet agreed at the outset will mean that both sides know where they stand.
6. Whenever and however the end of the relationship comes to an end, it's crucial to document what assistance the supplier will provide on exit. It's amazing how many signed contracts have an exit schedule which simply says "to be completed as soon as possible after contract signature". It's even more amazing that the schedule is not looked at again until the eve of termination, by which time relations between supplier and customer may not be the best. Exit should be recognised and treated as a project in itself, and documented as such. Agreeing a detailed exit schedule in advance will resolve many uncertainties at what is bound to be a tense time.
7. What should the exit schedule address? It will vary from contract to contract, of course, but customers will want to ensure that they end up with (or at least have the option of ending up with) the means of providing the relevant services. This might mean hand back of premises or physical property, and these will need to be in a proper state so the customer can use them. Think also about handover of know how. It's no use having the kit if your people don't know how to use it. There may be other less obvious material which will be needed such as data which the supplier may have collected over the life of the project.
8. Employees may be a central issue on exit. From a practical, operational perspective, particular individuals may be key to the delivery of the service. From a legal perspective, TUPE may well impact on the rights and liabilities of the supplier, customer and the relevant employees (just as it might have done on entry into the contract). TUPE can present significant uncertainties on exit, so it may be best to deal with it at the outset.
9. Who pays for exit? It's crucial to decide this up-front. Obviously much will depend on the strength of your bargaining position, but all one-way traffic may not be a great idea. Suppliers perform best when incentivised. Given that the supplier may be reluctant about giving up the contract, it's not surprising that it may be tempted to "work to rule" in this situation. And working to rule often isn't good enough on exit when you need the supplier to go the extra mile. Some financial reward to smooth the way may work wonders.
10. Finally, just as contracts need to be flexible, so do exit schedules. As the shape of the contract evolves, it's important to ensure that the exit arrangements reflect this. Any major change should include a review of the impacts on exit. And it's good practice to review and update the exit schedule annually.`,'https://www.freeiconspng.com/uploads/company-icon--desktop-business-icons--softiconsm-23.png'),
  ('MAY',`1. Make sure the services are described in the contract and its schedules. It sounds obvious, but experience shows that many ignore this basic point, and live to rue the day. After all the fuzzy sales talk, it's easy to think you and the supplier are of the same mind about what is going to be delivered. But you need to write it down. And it's amazing how often writing it down shows there are some things you disagree on. When you have written it down, think about whether there is ambiguity. Suppose the cost of the service is to be by reference to the number of employees who use it. Is "employees" enough? Would it be better for you to refer to "full time equivalents"? The financial consequences of loose drafting can be very significant.
2. Measuring the standard to which the service is delivered is crucial. The supplier will have some well worn objective measures, response times, service availability, etc. Think about whether these really reflect what is important to your business (as opposed to what the supplier is confident it can do). If not, think about alternative measures. It is also worth running some mock scenarios against the service credits to test how they might apply in live situations. Does it really matter if there is a service interruption at 4am? Should it have the same consequences as a service interruption at 4pm? It's also worth making sure that the financial impact of any service credits is realistic: token service credits are pointless; punitive service credits can damage the relationship. Be prepared to think innovatively about service measurement and reward. For example, some current thinking involves rewards going direct to the supplier's delivery team as personal bonuses.
3. FM contracts are a long game, and things change. Will the service you buy today meet your business' needs in three years time? In reality, the shape of your business is likely to change significantly through things such as organic growth or even shrinkage, acquisition or divestment, taking on new sites, consolidating others, establishing new service lines, dropping others. It's vital that the contract has built in enough flexibility – in terms of services and pricing – to allow you to manage business change. Your lawyers will be able to advise you on the options for change control. In many instances it is important to be able to compel the supplier to accept changes. As well as a clear change management process, effective contracts will have transparent pricing for specific service lines so that both parties can approach change with a degree of certainty.
4. You're expecting great things, but what if the service is woeful, and threatens your business? It's critical to build in rights to terminate when the supplier does not deliver to its promises. Most contracts will contain a general termination right where the supplier is in material breach. Think about whether this needs to be supplemented with specific rights of termination for some performance defaults, for example failure to achieve service levels for three consecutive months. Specific rights can give a degree of certainty in difficult situations. On the subject of difficult situations, think about a contractual dispute resolution procedure. This can provide for escalation through to senior management if an intractable dispute arises. It is also worth thinking about alternatives to litigation for resolving disputes. Arbitration can work well, and it's confidential so there's less chance of bad publicity. But take care in multi‑party situations. If some parties are signed up to arbitration and others are not, life can get messy.
5. Disputes are one thing, but the relationship may not work for commercial reasons. What looks like a good deal today can turn out to be uncompetitive in three years' time. An effective price and quality benchmarking process should help control this risk, but sometimes it is necessary to terminate early. A well drawn agreement will give this right to terminate for convenience and provide for the financial consequences of this. It's best to avoid more nebulous statements about how this sum will be calculated, such as "the supplier's unrecovered costs plus an element of profit". This just provides scope for argument. A fully worked formula or spreadsheet agreed at the outset will mean that both sides know where they stand.
6. Whenever and however the end of the relationship comes to an end, it's crucial to document what assistance the supplier will provide on exit. It's amazing how many signed contracts have an exit schedule which simply says "to be completed as soon as possible after contract signature". It's even more amazing that the schedule is not looked at again until the eve of termination, by which time relations between supplier and customer may not be the best. Exit should be recognised and treated as a project in itself, and documented as such. Agreeing a detailed exit schedule in advance will resolve many uncertainties at what is bound to be a tense time.
7. What should the exit schedule address? It will vary from contract to contract, of course, but customers will want to ensure that they end up with (or at least have the option of ending up with) the means of providing the relevant services. This might mean hand back of premises or physical property, and these will need to be in a proper state so the customer can use them. Think also about handover of know how. It's no use having the kit if your people don't know how to use it. There may be other less obvious material which will be needed such as data which the supplier may have collected over the life of the project.
8. Employees may be a central issue on exit. From a practical, operational perspective, particular individuals may be key to the delivery of the service. From a legal perspective, TUPE may well impact on the rights and liabilities of the supplier, customer and the relevant employees (just as it might have done on entry into the contract). TUPE can present significant uncertainties on exit, so it may be best to deal with it at the outset.
9. Who pays for exit? It's crucial to decide this up-front. Obviously much will depend on the strength of your bargaining position, but all one-way traffic may not be a great idea. Suppliers perform best when incentivised. Given that the supplier may be reluctant about giving up the contract, it's not surprising that it may be tempted to "work to rule" in this situation. And working to rule often isn't good enough on exit when you need the supplier to go the extra mile. Some financial reward to smooth the way may work wonders.
10. Finally, just as contracts need to be flexible, so do exit schedules. As the shape of the contract evolves, it's important to ensure that the exit arrangements reflect this. Any major change should include a review of the impacts on exit. And it's good practice to review and update the exit schedule annually.`,'https://www.freeiconspng.com/uploads/company-icon--desktop-business-icons--softiconsm-23.png'),
  ('YAHYA','Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor. Duis mollis, est non commodo luctus.','https://www.freeiconspng.com/uploads/company-icon--desktop-business-icons--softiconsm-23.png'),
  ('TURKI','Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor. Duis mollis, est non commodo luctus.','https://www.freeiconspng.com/uploads/company-icon--desktop-business-icons--softiconsm-23.png');

  INSERT INTO clients(client_name,client_type) 
  VALUES ('dunkin donuts', 'Cafe'),
   ('Macdonalds', 'Resturant'),
   ('holidayInn', 'Hotel'),
   ('RiyadhPark', 'Mall'),
   ('Alaskar', 'Residencial');

  INSERT INTO contracts (contract_period,contract_status,contract_issue_date,company_id,client_id)
  VALUES(6,'Active','2019-01-14',1,1),
  (6,'Active','2019-01-14',1,2),
  (6,'Active','2019-01-14',1,3),
  (6,'Pending','2019-01-14',2,4),
  (6,'Expired','2019-01-14',3,5);

